name: InPAC_Remote
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: Question 1
        # Sourced from: https://github.com/umuttopalak/pythonanywhere-deploy-action
        uses: ./.github/actions/release
        with:
          host: www.pythonanywhere.com
          username: inpac
          api_token: ${{ secrets.PA_API_TOKEN }}
          domain_name: inpac.pythonanywhere.com
          console_id: 35332376
          directory: /home/inpac
          github_username: ${{ github.actor }}
          # use github secrets for this
          github_token: ${{ secrets.GH_TOKEN }}
          github_repo_name: Max-Herbold/inpac_remote
