name: InPAC_Remote
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -r requirements-test.txt

      - name: Run tests
        run: |
          pytest
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Request remote pull
        # send a get request https://inpac.pythonanywhere.com/api/update/update
        run: |
          echo "PULL_STATUS=$(curl -s -o /dev/null -w %{http_code} -X GET -H Update-Token:${{secrets.UPDATE_TOKEN}} https://inpac.pythonanywhere.com/api/update/update)" >> $GITHUB_ENV
          echo "status: $PULL_STATUS"
      - name: Reload remote
        # dont run this step if the previous step failed
        if: env.PULL_STATUS == 200
        run: |
          echo `reload_status=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H '{ Authorization: `Token ${{secrets.PA_API_TOKEN}}` }' https://www.pythonanywhere.com/api/v0/user/inpac/webapps/inpac.pythonanywhere.com/reload/)` >> $GITHUB_ENV
          echo "status: ${{ env.reload_status }}"
