name: InPAC_Remote
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -r requirements-test.txt

      - name: Run tests
        run: |
          pytest
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Deploy to PythonAnywhere
        # Sourced from: https://github.com/umuttopalak/pythonanywhere-deploy-action
        uses: ./.github/actions/release
        with:
          host: www.pythonanywhere.com
          username: inpac
          api_token: ${{ secrets.PA_API_TOKEN }}
          domain_name: inpac.pythonanywhere.com
          console_id: 35332376
          directory: /home/inpac/inpac_remote
          github_username: ${{ github.actor }}
          # use github secrets for this
          github_token: ${{ secrets.GH_TOKEN }}
          github_repo_name: Max-Herbold/inpac_remote
